### ISSUE TITLE
requests >=2.10.0?

### ISSUE THREAD

**Issue by theunraveler** [reubano/meza#12]
Hello. I'm trying to install `meza` with `pip-tools`, but am getting a dependency constraint resolution error between this package and the `awsebcli` package. `meza` calls for `requests >= 2.10.0`, and `awsebcli` calls for `<=2.9.1`.

Is there a specific reason for `meza` to require `>= 2.10.0`? Could this requirement be loosened at all, since `requests` is pretty stable?

Thanks!

**Comment by reubano** [comment]
No reason in particular other than I usually bump the requirements whenever I upgrade. Feel free to submit a PR. As long as the tests pass I'll happily merge it.

**Comment by reubano** [comment]
Something like `>= 2.9.1` should do.

**Comment by theunraveler** [comment]
Thanks. I made a PR that loosens it to `2.0.0`, since `requests` is a fairly stable package. https://github.com/reubano/meza/pull/13
