### ISSUE TITLE
Column ordering is not preserved

### ISSUE THREAD

**Issue by amirouche** [reubano/meza#17]
At least [before Python 3.7](https://twitter.com/raymondh/status/850102884972675072) column ordering is not kept. I am new to the field of data science and data engineering. I am wondering whether column order is significant in a table.

WDYT?

**Comment by reubano** [comment]
Hi @amirouche, dictionary order is considered an implementation detail and not relevant for most use cases. If you require a specific order, you can use `collections.OrderedDict`. 

```python
records = [{'a': 1, 'b': 2}, {'a': 3, 'b': 4}]
[OrderedDict(sorted(r.items(), key=lambda t: t[0])) for r in records]
```
