### ISSUE TITLE
No module named http

### ISSUE THREAD

**Issue by xueyoo** [reubano/meza#21]
https://docs.python.org/2.7/library/httplib.html
python 2 using httplib, and python3, using  http.client

so when I import meza.io module, and it will show error "no module named http"

**Comment by reubano** [comment]
Thanks for this! I have a patch in the works. Any guess why the [py2 travis test](https://travis-ci.org/reubano/meza/jobs/380845436) still passes?

**Comment by EbtsamSaad** [comment]
I facing the same problem how can you solve this @xueyoo  @reubano

**Comment by reubano** [comment]
Thanks for the info. Just dropped support for py2 via a56b927. However, I'm happy to accept a PR off of v0.41.1 (cb28f487).

**Comment by jaraco** [comment]
As this issue only affects Python 2, let's consider this wontfix. Feel free to revive with a PR if necessary.
