### ISSUE TITLE
Rename main branch to main

### ISSUE THREAD

**Issue by jaraco** [reubano/meza#62]
@reubano How do you feel about renaming the main branches of these projects (meza, csv2ofx) to "main"? It's the new default for git and many projects have moved to it. It would be nice for me for these to be consistent with other projects. I can help work through any transitional issues (though in my experience, it's pretty straightforward). As the project owner, you'll either have to grant me access or do it yourself ([docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch)). Let me know how you'd like to proceed.

**Comment by reubano** [comment]
Is better to change the branch or rename it?

**Comment by jaraco** [comment]
If GitHub allows you to rename it, that's probably best, as that should handle much of the housekeeping (at least within GitHub).

Here's [the routine I've used in the past](https://github.com/jaraco/jaraco.xonsh/blob/2dee2150fc363aab5bc04ae1c93d349c2d2782a2/jaraco/xonsh.xsh#L301-L314). It looks like I simply push master to main, then set the default branch in GitHub, repoint PRs and reconfigure RTD, delete the master branch, then take care of some other housekeeping on the local clone.

I think the GitHub instructions might automate some of that (especially repointing PRs) if you use their UI in the admin.

**Comment by reubano** [comment]
Ok, I renamed it in the UI. Let me know if anything breaks.

**Comment by jaraco** [comment]
Fantastic!

Here's what I did locally for my fork-based checkout:

```
 meza main @ git fetch upstream
From https://github.com/reubano/meza
 * [new branch]      main       -> upstream/main
 meza main @ git remote set-head upstream -a
upstream/HEAD set to main
 meza main @ git pull upstream
You asked to pull from the remote 'upstream', but did not specify
a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line.
 meza main @ git branch -u upstream/main main
branch 'main' set up to track 'upstream/main'.
 meza main @ git pull upstream
Already up to date.
```

I'd like to see the same for csv2ofx. Should I file a similar issue there?
